# User defined entries should be added to this file not to /etc/sysctl.d/* as
# that directory is not backed-up by default and will not survive a reimage

net.ipv4.tcp_congestion_control = bbr
net.core.netdev_max_backlog = 3000