name: Build ImmortalWrt-25.12 for x86_64

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-25.12
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update > /dev/null
        sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/nantayo/My-Pkg/master/openwrt) > /dev/null
        sudo -E apt-get -qq autoremove --purge > /dev/null
        sudo -E apt-get -qq clean > /dev/null
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH --single-branch --depth=1 openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        echo "FILE_DATE=$(date +"%Y%m%d")" >> $GITHUB_ENV

    - name: Update & Install feeds
      run: |
        chmod +x x86/64/diy/diy.sh
        cd openwrt
        ./scripts/feeds update -a
        $GITHUB_WORKSPACE/x86/64/diy/diy.sh
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: SSH connect to Actions
      uses: P3TERX/ssh2actions@main
      if: ${{ github.event.inputs.ssh == 'true' }}

    - name: Adjust source code
      working-directory: ./openwrt
      run: |
        patch -p1 -f < $GITHUB_WORKSPACE/x86/64/2-7505/simplify-i915-firmware.patch
        patch -p1 -f < $GITHUB_WORKSPACE/x86/64/2-7505/simplify-intel-microcode.patch

    - name: Load custom config
      run: |
        rm -rf openwrt/files openwrt/.config
        mv x86/64/2-7505/files x86/64/2-7505/.config openwrt/

    - name: Download package
      working-directory: ./openwrt
      run: |
        make defconfig
        make download -j$(( $(nproc) * 2 ))
        find dl -size -1k -exec rm -f {} \;

    - name: Compile firmware
      run: |
        chmod -R 755 openwrt
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(( $(nproc) + 1 )) || make -j1 V=s
        mv bin/targets/x86/64/*efi.img.gz 2-7505.img.gz
        rm -rf bin/targets/x86/64/*

    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      with:
        tag_name: OpenWrt_x86_64_${{ env.FILE_DATE }}
        files: openwrt/2-7505.img.gz

    - name: Delete old releases
      uses: mgz0227/delete-older-releases@master
      with:
        keep_latest: 2
        delete_tags : true
        delete_tag_pattern : x86_64
